### BASICS OF PYTHON

In [ ]:
# comments

In [8]:
''' 
comments
'''

' \ncomments\n'

In [10]:
print("a")

a


In [11]:
name = "Alice"
print("Hello,", name)

Hello, Alice


In [12]:
name.isalnum()

True

In [13]:
name.islower()


False

ModuleNotFoundError: No module named 'numpy'

In [15]:
!pip3 install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 5.3 MB 3.9 MB/s eta 0:00:01
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.


In [16]:
import numpy as np


In [17]:
my_list = [1,2,34,4,5]

In [18]:
arr = np.array(my_list)

In [19]:
print(arr)

[ 1  2 34  4  5]


In [20]:
print(my_list)

[1, 2, 34, 4, 5]


In [21]:
type(arr)

numpy.ndarray

In [22]:
arr.shape


(5,)

In [26]:
my_list1 = [1,2,34,4,5]
my_list2 = [4,6,67,78,43]
my_list3 = [5,7,3344,75,34]
my_list4 = [6,298,3,89,23]
arr = np.array([my_list1,my_list2,my_list3,my_list4])

In [27]:
arr

array([[   1,    2,   34,    4,    5],
       [   4,    6,   67,   78,   43],
       [   5,    7, 3344,   75,   34],
       [   6,  298,    3,   89,   23]])

In [28]:
arr.shape

(4, 5)

In [29]:
arr.reshape(5,4)

array([[   1,    2,   34,    4],
       [   5,    4,    6,   67],
       [  78,   43,    5,    7],
       [3344,   75,   34,    6],
       [ 298,    3,   89,   23]])

In [31]:
arr.reshape(10,2)

array([[   1,    2],
       [  34,    4],
       [   5,    4],
       [   6,   67],
       [  78,   43],
       [   5,    7],
       [3344,   75],
       [  34,    6],
       [ 298,    3],
       [  89,   23]])

In [33]:
arr.transpose()

array([[   1,    4,    5,    6],
       [   2,    6,    7,  298],
       [  34,   67, 3344,    3],
       [   4,   78,   75,   89],
       [   5,   43,   34,   23]])

In [42]:
arr = np.arange(0 , 10 , step = 3)

In [43]:
arr


array([0, 3, 6, 9])

In [45]:
np.linspace(1 , 10 , 200)

array([ 1.        ,  1.04522613,  1.09045226,  1.13567839,  1.18090452,
        1.22613065,  1.27135678,  1.31658291,  1.36180905,  1.40703518,
        1.45226131,  1.49748744,  1.54271357,  1.5879397 ,  1.63316583,
        1.67839196,  1.72361809,  1.76884422,  1.81407035,  1.85929648,
        1.90452261,  1.94974874,  1.99497487,  2.04020101,  2.08542714,
        2.13065327,  2.1758794 ,  2.22110553,  2.26633166,  2.31155779,
        2.35678392,  2.40201005,  2.44723618,  2.49246231,  2.53768844,
        2.58291457,  2.6281407 ,  2.67336683,  2.71859296,  2.7638191 ,
        2.80904523,  2.85427136,  2.89949749,  2.94472362,  2.98994975,
        3.03517588,  3.08040201,  3.12562814,  3.17085427,  3.2160804 ,
        3.26130653,  3.30653266,  3.35175879,  3.39698492,  3.44221106,
        3.48743719,  3.53266332,  3.57788945,  3.62311558,  3.66834171,
        3.71356784,  3.75879397,  3.8040201 ,  3.84924623,  3.89447236,
        3.93969849,  3.98492462,  4.03015075,  4.07537688,  4.12

## copy and brodcasting

arr1 = arr (with same reference)

arr1.copy() (other memory space and work seperately)


In [51]:
np.ones(4)

array([1., 1., 1., 1.])

In [52]:
np.ones(4 , dtype = int)

array([1, 1, 1, 1])

In [54]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [55]:
arr_exp = np.random.rand(3,3)

In [56]:
arr_exp

array([[0.39220566, 0.05033379, 0.55538812],
       [0.89330093, 0.83134302, 0.26643294],
       [0.49755492, 0.75136769, 0.01938078]])

In [57]:
arr_exp1 = np.random.randn(3,3)

In [58]:
arr_exp1


array([[ 0.85190917, -0.32002475, -0.3627858 ],
       [ 0.25239869,  0.55856519, -1.82404424],
       [-0.6939215 , -1.4663269 ,  1.65092846]])